datasets:
  pascal_voc:
    name: &dataset_name 'pascal_voc2012'
    type: 'VOCDetection'
    root: &root_dir '~/dataset'
    splits:
      train:
        dataset_id: &pascal_train !join [*dataset_name, '/train']
        params:
          root: *root_dir
          image_set: 'train'
          year: '2012'
          download: False
          transforms_compose_cls: 'CustomCompose'
          transforms_params:
            - type: 'CustomRandomResize'
              params:
                min_size: 256
                max_size: 1026
            - type: 'CustomRandomHorizontalFlip'
              params:
                p: 0.5
            - type: 'CustomRandomCrop'
              params:
                size: 513
            - type: 'CustomToTensor'
              params:
            - &normalize
              type: 'CustomNormalize'
              params:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &pascal_val !join [*dataset_name, '/val']
        params:
          root: *root_dir
          image_set: 'val'
          year: '2012'
          download: False
          transforms_compose_cls: 'CustomCompose'
          transforms_params: &val_transform
            - type: 'CustomRandomResize'
              params:
                min_size: 513
                max_size: 513
            - type: 'CustomToTensor'
              params:
                converts_sample: True
                converts_target: True
            - *normalize


models:
  teacher_model:
    name: &teacher_model_name 'ssd_teacher_vgg16'
    params:
      pretrained: True
      progress: True
      num_classes: 91
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/coco2017/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: 'ssd_model'
    params:
      pretrained: True
      pretrained_backbone_name: 'vgg16'
      progress: True
      num_classes: 91
      backbone_config:
        name: 'splittable_vgg16'
        params:
          num_classes: 91
          pretrained: True
          bottleneck_config:
            name: 'compression_vgg_custom_relu'
            coverage: 18
            params:
              bottleneck_channel: &bch 6
              bottleneck_idx: 13
              output_channel: 64 ###########
              compressor_transform_params:
                - type: 'SimpleQuantizer'
                  params:
                    num_bits: 8
              decompressor_transform_params:
                - type: 'SimpleDequantizer'
                  params:
                    num_bits: 8
          vgg_name: 'ssd300_vgg16'
          pre_transform_params:
          skips_avgpool: True
          skips_fc: True
        ckpt:
      backbone_kwargs:
        return_layer_dict:
          bottleneck_layer: '1'
          layer20: '20'
          layer22: '22'
        in_channels_list: [256, 512, 1024, 2048]
        out_channels: [512,1024,512,256,256,256]
        analysis_config:
          analyzes_after_compress: True
          analyzer_configs:
            - type: 'FileSizeAnalyzer'
              params:
                unit: 'KB'
        analyzable_layer_key: 'bottleneck_layer'
      start_ckpt_file_path: './resource/ckpt/coco2017/supervised_compression/ghnd-bq/coco2017-ssd300_vgg16-bq12ch_ssd300_vgg16_lr10_5_ch6_with_norm_custom_relu.pt'
    experiment: &student_experiment !join [*dataset_name, '-ssd300_vgg16-bq', *bch, 'ch_ssd300_vgg16_lr10_5_ch6_with_norm_custom_relu']
    ckpt: !join ['./resource/ckpt/coco2017/supervised_compression/ghnd-bq/', *student_experiment, '.pt']

train:
  log_freq: 1000
  epoch_to_update: &epoch_to_update 20
  num_epochs: *epoch_to_update
  train_data_loader:
    dataset_id: *coco_train
    random_sample: True
    num_workers: 8
    batch_sampler:
      type: 'GroupedBatchSampler'
      params:
        aspect_ratio_group_factor: 3
        batch_size: 16
    collate_fn: 'coco_collate_fn'
    cache_output:
  val_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 16
    num_workers: 8
    collate_fn: 'coco_collate_fn'
  teacher:
    forward_proc: 'forward_batch'
    sequential: []
    special:
      type: 'SSDHead'
      params:
        head_ssd:
          sequential: ['backbone.features.layer1', 'backbone.features.layer3', 'backbone.features.layer6', 'backbone.features.layer8', 'backbone.features.layer11', 'backbone.features.layer13', 'backbone.features.layer15', 'backbone.features.layer18', 'backbone.features.layer20', 'backbone.features.layer22']
    frozen_modules: []
    forward_hook:
      input: []
      output: ['seq.backbone.features.layer1', 'seq.backbone.features.layer3', 'seq.backbone.features.layer6', 'seq.backbone.features.layer8', 'seq.backbone.features.layer11', 'seq.backbone.features.layer13', 'seq.backbone.features.layer15', 'seq.backbone.features.layer18', 'seq.backbone.features.layer20', 'seq.backbone.features.layer22']
    wrapper: 'DataParallel'
    requires_grad: False
  student:
    forward_proc: 'forward_batch'
    adaptations:
    sequential: []
    special:
      type: 'SSDHead'
      params:
        head_ssd:
          sequential: ['backbone.features']
    frozen_modules: []
    forward_hook:
      input: []
      output: ['seq.backbone.features.body.bottleneck_layer', 'seq.backbone.features.body.layer20', 'seq.backbone.features.body.layer22']
    wrapper: 'DistributedDataParallel'
    requires_grad: True
  optimizer:
    type: 'Adam'
    params:
      lr: 0.001
  scheduler:
    type: 'MultiStepLR'
    params:
      milestones: [5, 15]
      gamma: 0.1
  criterion:
    type: 'GeneralizedCustomLoss'
    org_term:
      factor: 0.0
    sub_terms:
      layer1:
        criterion:
          type: 'MSELoss'
          params:
            reduction: 'sum'
        params:
          input:
            is_from_teacher: False
            module_path: 'seq.backbone.features.body.bottleneck_layer'
            io: 'output'
          target:
            is_from_teacher: True
            module_path: 'seq.backbone.features.layer18'
            io: 'output'
        factor: 1.0
      layer2:
        criterion:
          type: 'MSELoss'
          params:
            reduction: 'sum'
        params:
          input:
            is_from_teacher: False
            module_path: 'seq.backbone.features.body.layer20'
            io: 'output'
          target:
            is_from_teacher: True
            module_path: 'seq.backbone.features.layer20'
            io: 'output'
        factor: 1.0
      layer3:
        criterion:
          type: 'MSELoss'
          params:
            reduction: 'sum'
        params:
          input:
            is_from_teacher: False
            module_path: 'seq.backbone.features.body.layer22'
            io: 'output'
          target:
            is_from_teacher: True
            module_path: 'seq.backbone.features.layer22'
            io: 'output'
        factor: 1.0
      
      

test:
  test_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 1
    num_workers: 8
    collate_fn: 'coco_collate_fn'
