datasets:
  ilsvrc2012:
    name: &dataset_name 'cifar100'
    type: 'CIFAR100'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &cifar_train !join [*dataset_name, '/train']
        params:
          train: True
          root: *root_dir
          transform_params:
            - type: 'RandomResizedCrop'
              params:
                size: &input_size [32, 32]
            - type: 'RandomHorizontalFlip'
              params:
                p: 0.5
            - &totensor
              type: 'ToTensor'
              params:
            - &normalize
              type: 'Normalize'
              params:
                mean: [0.5071, 0.4867, 0.4408]
                std: [0.2675, 0.2565, 0.2761]
      val:
        dataset_id: &cifar_val !join [*dataset_name, '/val']
        params:
          root: *root_dir
          transform_params:
            - *totensor
            - *normalize

models:
  model:
    name: 'SplitClassifier'
    params:
      num_classes: 100
      org_model_ckpt_file_path_or_url: 'resource/ckpt/cifar100/supervised_compression/ghnd-bq/cifar100-mobilenet_v3_small-bq6ch_from_mobilenet_v3_small.pt'
      bottleneck_config:
        name: 'mobilenet_v3_small_compression_cov2'
        start_coverage: 1
        end_coverage: 3
        params:
          bottleneck_channel: &bch 6
          bottleneck_idx: 6 #########
          output_channel: 24
          compressor_transform_params:
            - type: 'SimpleQuantizer'
              params:
                num_bits: 8
          decompressor_transform_params:
            - type: 'SimpleDequantizer'
              params:
                num_bits: 8
      mobilenet_name: 'mobilenet_v3_small'
      pre_transform_params:
      skips_avgpool: False
      skips_fc: False
      analysis_config:
        analyzes_after_compress: True
        analyzer_configs:
          - type: 'FileSizeAnalyzer'
            params:
              unit: 'KB'
    classification_model:
      name: &teacher_model_name 'mobilenet_v3_small'
      params:
        num_classes: 100
        pretrained: False
      ckpt: !join ['./resource/ckpt/cifar100/supervised_compression/ghnd-bq/', *dataset_name, '-mobilenet_v3_small-bq', *bch, 'ch_from_mobilenet_v3_small', '.pt']
    experiment: &experiment !join [*dataset_name, '-mobilenet_v3_small-bq', *bch, 'ch_from_', *teacher_model_name, '_finetuning']
    ckpt: !join ['./resource/ckpt/cifar100/supervised_compression/ghnd-bq/', *experiment, '.pt']

train:
  log_freq: 1000
  epoch_to_update: &epoch_to_update 10
  num_epochs: *epoch_to_update
  train_data_loader:
    dataset_id: *cifar_train
    random_sample: True
    batch_size: 256
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *cifar_val
    random_sample: False
    batch_size: 32
    num_workers: 16
  model:
    forward_hook:
      input: []
      output: ['bottleneck_layer']
    wrapper: 'DistributedDataParallel'
    requires_grad: True
  optimizer:
    type: 'Adam'
    params:
      lr: 0.001
  scheduler:
    type: 'MultiStepLR'
    params:
      milestones: [5, 8]
      gamma: 0.1
  criterion:
    type: 'GeneralizedCustomLoss'
    org_term:
      criterion:
        type: 'CrossEntropyLoss'
        params:
          reduction: 'mean'
      factor: 1.0
    sub_terms:
      bpp:
        criterion:
          type: 'BppLoss'
          params:
            entropy_module_path: 'bottleneck_layer'
            reduction: 'batchmean'
        factor: 1

test:
  test_data_loader:
    dataset_id: *cifar_val
    random_sample: False
    batch_size: 1
    num_workers: 16
